
connect sys/Ch1r1m0y0_Pl4y3r0 as sysdba;


create or replace directory copias as '/home/oracle/datapum';
grant read, write on directory copias to system;

-- REGISTRO_LGS

-- ***************************************************************************
-- 			REGISTRO_LGS
-- ***************************************************************************

GRANT UNLIMITED TABLESPACE TO REGISTRO_LGS;

GRANT RESOURCE, CONNECT,CREATE VIEW, CTXAPP TO REGISTRO_LGS;
GRANT EXECUTE ON CTXSYS.CTX_CLS TO REGISTRO_LGS; 
GRANT EXECUTE ON CTXSYS.CTX_DDL TO REGISTRO_LGS; 
GRANT EXECUTE ON CTXSYS.CTX_DOC TO REGISTRO_LGS; 
GRANT EXECUTE ON CTXSYS.CTX_OUTPUT TO REGISTRO_LGS; 
GRANT EXECUTE ON CTXSYS.CTX_QUERY TO REGISTRO_LGS; 
GRANT EXECUTE ON CTXSYS.CTX_REPORT TO REGISTRO_LGS; 
GRANT EXECUTE ON CTXSYS.CTX_THES TO REGISTRO_LGS; 
GRANT EXECUTE ON CTXSYS.CTX_ULEXER TO REGISTRO_LGS;

GRANT EXECUTE ON "SYS"."DBMS_CRYPTO" TO REGISTRO_LGS;


GRANT EXECUTE ON Java_jars.selloTiempo TO REGISTRO_LGS;
GRANT EXECUTE ON Java_jars.Firma TO REGISTRO_LGS;
GRANT EXECUTE ON Java_jars.S3_mgr TO REGISTRO_LGS;
GRANT EXECUTE ON Java_jars.XADES TO REGISTRO_LGS;
GRANT EXECUTE ON Java_jars.validador TO REGISTRO_LGS;
GRANT EXECUTE ON Java_jars.pl_utils TO REGISTRO_LGS;
GRANT EXECUTE ON Java_jars.NOTIFICACIONES TO REGISTRO_LGS;


-- SERVICIOS_REDMOON
GRANT SELECT ON SERVICIOS_REDMOON.REDES_DECONFIANZA TO REGISTRO_LGS;
GRANT EXECUTE ON SERVICIOS_REDMOON.pkChkSesion TO REGISTRO_LGS;
